# -*- coding: utf-8 -*-
"""age-calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jv_3jtMAS5HrR9ghuV9oE-vcwWVNx-KN
"""

code = """
import streamlit as st
import datetime

st.title("📅 만나이 계산기")

year = st.number_input("출생 연도", min_value=1900, max_value=2100, step=1)
month = st.number_input("출생 월", min_value=1, max_value=12, step=1)
day = st.number_input("출생 일", min_value=1, max_value=31, step=1)

if st.button("계산하기"):
    try:
        birth = datetime.date(int(year), int(month), int(day))
        today = datetime.date.today()
        age = today.year - birth.year
        if (today.month, today.day) < (birth.month, birth.day):
            age -= 1
        st.success(f"현재 만나이는 {age}세입니다.")
    except:
        st.error("올바른 날짜를 입력해 주세요.")
"""

with open("app.py", "w", encoding="utf-8") as f:
    f.write(code)

print("✅ app.py 파일 생성 완료")

with open("requirements.txt", "w") as f:
    f.write("streamlit\n")

print("✅ requirements.txt 파일 생성 완료")